--Yulia Flenova N01342767
-- LAB 12

CREATE TABLE copy_countries AS SELECT * FROM countries; 

CREATE OR REPLACE PROCEDURE DELETE_ROWS(P_TABLE_NAME IN VARCHAR2, P_NUM_ROWS OUT NUMBER) IS
BEGIN 
    EXECUTE IMMEDIATE 'DELETE FROM ' || P_TABLE_NAME;
    P_NUM_ROWS := SQL%ROWCOUNT;
END;

DECLARE
    V_NUM_ROWS NUMBER(4);
BEGIN   
    DELETE_ROWS('COPY_COUNTRIES', V_NUM_ROWS);
    DBMS_OUTPUT.PUT_LINE('ROWS DELETED ' || V_NUM_ROWS);
END;


CREATE OR REPLACE PROCEDURE HOW_MANY_ROWS (P_TABLE_NAME VARCHAR2, P_NUM_ROWS OUT NUMBER) IS
    V_STMT VARCHAR2(200);
BEGIN
    V_STMT := 'SELECT count(*) FROM ' || P_TABLE_NAME;
    EXECUTE IMMEDIATE V_STMT INTO P_NUM_ROWS;
END;

DECLARE
    V_NUM_ROWS NUMBER(4);
BEGIN
    HOW_MANY_ROWS('WF_COUNTRIES', V_NUM_ROWS);
    DBMS_OUTPUT.PUT_LINE(V_NUM_ROWS);
END;

DECLARE
    V_NUM_ROWS NUMBER(4);
BEGIN
    HOW_MANY_ROWS('REGIONS', V_NUM_ROWS);
    DBMS_OUTPUT.PUT_LINE(V_NUM_ROWS);
END;

--==============================================================================
CREATE OR REPLACE PROCEDURE DISPLAY_DEPARTMENT_ID (P_TABLE_NAME VARCHAR2, P_MANAGER_ID NUMBER, P_DEPT_ID OUT NUMBER) IS
    V_STMT VARCHAR2(200);
BEGIN
    V_STMT := 'SELECT DEPARTMENT_ID FROM ' || P_TABLE_NAME || ' WHERE MANAGER_ID = ' || P_DEPT_ID;
    EXECUTE IMMEDIATE V_STMT INTO P_DEPT_ID;
EXCEPTION   
    WHEN NO_DATA_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('NO DATA FOUND');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('UNKNOWN ERROR');
END;

DECLARE
    V_DEPT_ID NUMBER(3);
BEGIN
    DISPLAY('DEPARTMENTS', 205, V_DEPT_ID);
    DBMS_OUTPUT.PUT_LINE(V_DEPT_ID);
END;

DECLARE
    V_DEPT_ID NUMBER(3);
BEGIN
    DISPLAY('EMPLOYEES', 205, V_DEPT_ID);
    DBMS_OUTPUT.PUT_LINE(V_DEPT_ID);
END;