-- Yulia Flenova N01342767
-- LAB 12 

-- 12.2

CREATE TABLE audit_table 
    (action  VARCHAR2(50),      
    user_name   VARCHAR2(30) DEFAULT USER,    
    last_change_date TIMESTAMP DEFAULT SYSTIMESTAMP); 

CREATE OR REPLACE TRIGGER INSERT_TRIGGER
AFTER INSERT ON EMPLOYEES FOR EACH ROW
DECLARE
BEGIN
    INSERT INTO AUDIT_TABLE (ACTION) VALUES ('INSERTING');
END;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (11, 'YULIA', 'FLENOVA', 'YF@G.COM', '1231231234', TO_DATE('17-SEP-02', 'DD-MON-RR'), 'AD_VP', 20230, NULL, NULL, NULL);

SELECT * FROM AUDIT_TABLE;

--==============================================================================
-- 12.3
CREATE OR REPLACE TRIGGER EMPLOYEE_AUDIT_TRIGGER
BEFORE INSERT OR DELETE ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDIT_TABLE (ACTION)
        VALUES ('INSERTED');
    ELSIF DELETING THEN
        INSERT INTO AUDIT_TABLE (ACTION)
        VALUES ('DELETED');
    END IF;
END;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (15, 'KIRILL', 'FLENOV', 'KF@G.COM', '1231231234', TO_DATE('17-SEP-02', 'DD-MON-RR'), 'AD_VP', 20230, NULL, NULL, NULL);

SELECT * FROM AUDIT_TABLE;

DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 15;

ALTER TABLE AUDIT_TABLE ADD (EMP_ID NUMBER);

CREATE OR REPLACE TRIGGER EMPLOYEE_AUDIT_TRIGGER
AFTER INSERT OR DELETE ON EMPLOYEES FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDIT_TABLE (EMP_ID, ACTION)
        VALUES ('INSERTED', :NEW.employee_id);
    ELSIF DELETING THEN
        INSERT INTO AUDIT_TABLE (EMP_ID, ACTION)
        VALUES ('DELETED', :OLD.employee_id);
    END IF;
END;

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES (20, 'IRINA', 'FLENOVA', 'IF@G.COM', '1231231234', TO_DATE('17-SEP-02', 'DD-MON-RR'), 'AD_VP', 20230, NULL, NULL, NULL);

SELECT * FROM AUDIT_TABLE;

DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 20;

SELECT * FROM AUDIT_TABLE;

--==============================================================================
-- 12.4
