// WEEK 6 
DECLARE 
    TYPE T_EMP_DEPT IS RECORD
    (
    FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
    DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE
    );
    
    V_EMP_DEPT T_EMP_DEPT;
    
BEGIN
    SELECT FIRST_NAME, DEPARTMENT_NAME  INTO V_EMP_DEPT
    FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    WHERE E.EMPLOYEE_ID=100;
    
    DBMS_OUTPUT.PUT_LINE(V_EMP_DEPT.FIRST_NAME || V_EMP_DEPT.DEPARTMENT_NAME);
END;

//===============================================================================

DECLARE 
    TYPE T_HIRE_DATE IS TABLE OF EMPLOYEES.HIRE_DATE%TYPE
    INDEX BY BINARY_INTEGER;
    
    V_EMP_DATE T_HIRE_DATE;
    
BEGIN
    FOR CUR_EMP IN (SELECT * FROM EMPLOYEES)LOOP
        V_EMP_DATE(CUR_EMP.EMPLOYEE_ID):= CUR_EMP.HIRE_DATE;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(V_EMP_DATE(100));
END;

//===============================================================================
DECLARE
    TYPE T_EMP_REC IS TABLE OF EMPLOYEES%ROWTYPE
    INDEX BY BINARY_INTEGER;
    
    V_EMP_REC T_EMP_REC;
    
BEGIN
     FOR EMP_REC IN 
     (SELECT * FROM EMPLOYEES)
     LOOP
        V_EMP_REC(EMP_REC.EMPLOYEE_ID):=EMP_REC;
        DBMS_OUTPUT.PUT_LINE(V_EMP_REC(EMP_REC.EMPLOYEE_ID).FIRST_NAME||'  '||V_EMP_REC(EMP_REC.EMPLOYEE_ID).SALARY);
     END LOOP;
     DBMS_OUTPUT.PUT_LINE(V_EMP_REC.COUNT);
END;

//===============================================================================
DECLARE
    V_FIRST_NAME VARCHAR(100);
BEGIN 
    SELECT FIRST_NAME INTO V_FIRST_NAME FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
EXCEPTION
    WHEN TOO_MANY_ROWS THEN 
    DBMS_OUTPUT.PUT_LINE('YOU MESSESD UP, TOO MANY ROWS');
END;

//===============================================================================
DECLARE
    V_FIRST_NAME VARCHAR(100);
    V_NUM NUMBER;
BEGIN 
    SELECT FIRST_NAME INTO V_FIRST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 1000;
    V_NUM := 100 / 0;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
EXCEPTION
    WHEN TOO_MANY_ROWS THEN 
        DBMS_OUTPUT.PUT_LINE('YOU MESSED UP, TOO MANY ROWS');
    WHEN NO_DATA_FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('YOU MESSED UP, EMPLOYEE DOEST EXIST');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('YOU MESSED UP, NOT SURE WHERE');
END;


