DECLARE 
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPES;
    CURSOR CUT_EMP_FIRST_NAME
    IS SELECT FIRST_NAME FROM EMPLOYEES;
BEGIN
    OPEN CUR_EMP_FIRST_NAME; // OPEN 
    FETCH CUR_EMP_FIRST_NAME INTO V_FIRST_NAME; 
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END;