-- WEEK 8 CLASS EXAMPLE

DECLARE 
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE := 100;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_FIRST_NAME
    FROM EMPLOYEES WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END;


CREATE OR REPLACE PROCEDURE P_GETFIRST_NAME IS
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE := 100;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_FIRST_NAME
    FROM EMPLOYEES WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END;

BEGIN 
    P_GETFIRST_NAME;
END;
--===============================================================================
CREATE OR REPLACE PROCEDURE P_GETFIRST_NAME (
    P_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE 
    )
    IS
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_FIRST_NAME
    FROM EMPLOYEES WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END;

BEGIN 
    P_GETFIRST_NAME(100);
END;
--===============================================================================
V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE DEFAULT 100;


BEGIN 
    P_GETFIRST_NAME(100);
    P_GETFIRST_NAME;
END;

--===============================================================================
-- READ ONLY VARIABLE
CREATE OR REPLACE PROCEDURE P_GETFIRST_NAME
(
    P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE := 100
)
IS 
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME INTO V_FIRST_NAME
    FROM EMPLOYEES WHERE EMPLOYEE_ID = P_EMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END;


--===============================================================================
-- 
CREATE OR REPLACE PROCEDURE P_GETFIRST_NAME
(
    P_EMPLOYEE_ID IN EMPLOYEES.EMPLOYEE_ID%TYPE := 100,
    P_FIRST_NAME OUT EMPLOYEES.FIRST_NAME%TYPE
)
IS 

BEGIN
    SELECT FIRST_NAME INTO P_FIRST_NAME
    FROM EMPLOYEES WHERE EMPLOYEE_ID = P_EMPLOYEE_ID;
END;

DECLARE
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN 
    P_GETFIRST_NAME(101, V_FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END;

--===============================================================================
CREATE OR REPLACE PROCEDURE GET_TAX_AMOUNT
(
    P_AMOUNT IN OUT NUMBER
)
IS
BEGIN
    P_AMOUNT := P_AMOUNT * 1.13;
--===============================================================================
DECLARE
    v_phone VARCHAR2(200) := '9051231234';
BEGIN
    format_phone(v_phone);
    DBMS_OUTPUT.PUT_LINE('Formatted phone number: ' || v_phone);
END;
