-- Week 10 Class example

create or replace PACKAGE PKG_EMP_DETAILS
    IS
    PROCEDURE
    PROC_PRINT_NAME (P_ID NUMBER);
    FUNCTION
    GET_SALARY(P_ID NUMBER)
    RETURN NUMBER;
END;


create or replace PACKAGE BODY PKG_EMP_DETAILS
IS
PROCEDURE PROC_PRINT_NAME ( P_ID NUMBER)
IS
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME
    INTO V_FIRST_NAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=P_ID;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END PROC_PRINT_NAME;
    FUNCTION
    GET_SALARY (P_ID NUMBER)
    RETURN NUMBER
    IS
    V_SAL EMPLOYEES.SALARY %TYPE;
BEGIN
    SELECT SALARY INTO V_SAL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=P_ID;
    RETURN V_SAL;
END GET_SALARY;
END;


DECLARE
    V_MYSAL EMPLOYEES.SALARY%TYPE;
    V_EMP_ID EMPLOYEES.EMPLOYEE_ID% TYPE:=100;
BEGIN
    V_MYSAL:=PKG_EMP_DETAILS.GET_SALARY(V_EMP_ID);
    DBMS_OUTPUT.PUT_LINE(V_MYSAL);
END;


DECLARE 
    V_MYSAL EMPLOYEES.SALARY%TYPE;
    V_EMP_ID EMPLOYEES.EMPLOYEE_ID% TYPE:=100;
BEGIN
    V_MYSAL:=PKG_EMP_DETAILS.GET_SALARY(V_EMP_ID);
    PKG_EMP_DETAILS.PROC_PRINT_NAME(V_EMP_ID);
    DBMS_OUTPUT.PUT_LINE(V_MYSAL);
END;


create or replace PACKAGE BODY PKG_EMP_DETAILS
IS
PROCEDURE
PROC_PRINT_NAME ( P_ID NUMBER)
IS
    V_FIRST NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    SELECT FIRST_NAME
    INTO V_FIRST_NAME
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=P_ID;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
END PROC_PRINT_NAME;
FUNCTION GET_RAISED_SALARY(P_ID
NUMBER) RETURN NUMBER
IS
V_SAL EMPLOYEES.SALARY%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('iN SIDE GET SALARY FUNCTION');
SELECT SALARY INTO V_SAL
FROM EMPLOYEES
WHERE EMPLOYEE_ID=P_ID;
V_SAL:=V_SAL*10;
RETURN V_SAL;
END GET_RAISED_SALARY;
FUNCTION
GET_SALARY(P_ID NUMBER)
RETURN NUMBER
IS
V_SAL
EMPLOYEES.SALARY%TYPE;
BEGIN
DBMS_OUTPUT.PUT_LINE('iN SIDE GET_SALARY FUNCTION'):
V_SAL:=GET_RAISED_SALARY(P_ID); 
RETURN V_SAL; 
END GET_SALARY;
END;