//Week 3 class examples
create table test(
col1 int,
col2 varchar(50))

select * from test

//DDL INSERT
insert into test values(100,'AAA'); //Implicit 
insert into test (col1, col2) values(101,'BBB'); //Explicit 

begin 
    insert into test(col1) values(101);
end;

//UPDATE DDL
UPDATE TEST
SET COL2='CCC'
WHERE COL1 = 102

DECLARE 
    V_COL1 INT=105;
    V_COL2 VARCHAR(50):='NEW TEST'
BEGIN 
    UPDATE TEST
    SET COL2=V_COL2
    WHERE COL1=V_COL1
END;

//DELETE DDL
DELETE FROM TEST WHERE COL1 =100

//MERGE DDL
SELECT * FROM EMPLOYEES

//CREATED TABLE
CREATE TABLE BONUS 
(EMPID NUMBER(6,2), 
BONUS_AMOUNT NUMBER (6,2))

INSERT INTO BONUS(EMPID)
(
SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE SALARY>500
)

SELECT EMPLOYEE_ID, SALARY, SALARY *.10
FROM EMPLOYEES
WHERE SALARY>500

SELECT * FROM BONUS

MERGE INTO BONUS B
USING EMPLOYEES E
ON (B.EMPID = E.EMPLOYEE_ID)
WHEN MATCHED THEN 
UPDATE SET B.BONUS_AMOUNT = E.SALARY*.10;

//Retrieving data 
DECLARE
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_LAST_NAME EMPLOYEES.LAST_NAME%TYPE;
BEGIN 
    SELECT FIRST_NAME , LAST_NAEM INTO V_FIRST_NAME, V_LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID=100;
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME|| V_LAST_NAME)
END;

// class practice 
DECLARE
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN 
    SELECT FIRST_NAME, DEPARTMENT_NAME
    INTO V_FIRST_NAME, V_DEPARTMENT_NAME
    FROM DEPARTMENTS D JOIN EMPLOYEES E 
    ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;
    DBMS_OUTPUT.PUT_LINE(V_FIRTS_NAME || V_DEPARTMENT_NAME);
END;

//SELECT DEPARTMENT_NAME INTO V_DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID=90;

