-- WEEK 12 CLASSS
CREATE OR REPLACE PROCEDURE P_DROP_TABLE (P_TABLE_NAME VARCHAR)
IS 
    V_STMT VARCHAR(100);
    BEGIN
    V_STMT:='DROP TABLE' || P_TABLE_NAME;
    DBMS_OUTPUT.PUT_LINE(V_STMT);
   -- EXECUTE IMMEDIATE V_STMT;
END;

CREATE TABLE TEST_101 (ID INT);

BEGIN 
    P_DROP_TABLE('TEST_101');
END;

select * from test_101

--====================
CREATE OR REPLACE PROCEDURE P_INSERT_TABLE (
    P_TABLE_NAME VARCHAR,
    P_ID NUMBER,
    P_NAME VARCHAR
)
IS 
    V_STMT VARCHAR(100);
BEGIN
    V_STMT := 'INSERT INTO ' || P_TABLE_NAME || ' VALUES ('||P_ID|| ', ''' ||P_NAME||''')';
    DBMS_OUTPUT.PUT_LINE(V_STMT);
    EXECUTE IMMEDIATE V_STMT;
END;

INSERT INTO TEST_102 VALUES(100,'AAA',

CREATE TABLE TEST_102 (
    P_ID NUMBER,
    P_NAME VARCHAR2(50)
);

BEGIN 
    P_INSERT_TABLE('TEST_102', 100, 'AAA');
END;

SELECT * FROM TEST_102;